#!/bin/bash

/*
* This checks if the Betty passed
* Args: None
*
* Returns: 0 passed
*          1 not passed
*/

function betty_checks() {

    betty_check_output=$(betty check)

    # Check if the Betty checks passed
    if [[ $betty_check_output == "Passed" ]];
	echo 0
    else
	 echo 1
	}

betty_checks
